# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: hey it's Ana
email: mail@heyitsana.com
author:
  name: Ana Santaheva
author_name: Ana Santaheva
description: >- # this means to ignore newlines until "baseurl:"
  Ana's site
url: heyitsana.com # the base hostname & protocol for your site, e.g. http://example.com

# permalink: /:slug.html

favicon: "./favicon.ico" # relative path to site's favicon

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Build settings
markdown: kramdown
remote_theme: riggraz/no-style-please
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
  gradient:
    - "#aef4ff"
    - "#3fbf8c"
    - "#ffd66b"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  style: compressed

# Navigation (used by nav.html)
nav:
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: CA Grid Live
    url: /grid/
  - title: Writing
    url: /writing/
  - title: Now
    url: /now/
  - title: Guestbook
    url: /guestbook/
  - title: Email
    url: /email/
